[package]
name = "storage-trait"
version = "0.1.4"
edition = "2021"
readme = "README.md"
description = "A simple k-v pair storage trait"
repository = "https://github.com/ZBcheng/storage-trait"
license = "MIT"


[dependencies]
dashmap = "5.3"
redis = "0.21.5"
